export default {
  backgroundImage: 'blobs.svg',
  padding: {
    mobile: '100px 0px 30px 0px',
    tablet: '100px 0px 30px 0px',
    desktop: '150px 0px 40px 0px',
  },
  margin: null,
  maxWidth: '1500px',
  alignItems: 'center',
  justify: 'space-evenly',
  borderShadow: '0px -20px 22px -23px #d9d9d9',
  cardOffset: {
    mobile: 0,
    tablet: 0,
    desktop: 0,
  },
  cards: [
    {
      maxWidth: '550px',
      padding: {
        mobile: '35px',
        tablet: '35px',
        desktop: '50px 42px',
      },
      margin: {
        mobile: '20px',
        tablet: '20px',
        desktop: '30px',
      },
      grid: {
        xs: 12,
        sm: 12,
        md: true,
        lg: null,
        xl: null,
      },
      heading: {
        text: 'Shop Womens',
        tag: 'h2',
        mobile: { size: 20, weight: 400, textAlign: 'center' },
        tablet: { size: 20, weight: 400 },
        desktop: { size: 24, weight: 400 },
      },
      copy: null,
      img: {
        src: 'shop-womens-landing.svg',
        padding: '20px',
        alt: 'shop womens',
        maxWidth: null,
        maxHeight: '150px',
      },
      cta: {
        href: '/search/params?section=womens',
        text: 'Start Shopping',
        padding: '0px',
        textTransform: 'capitalize',
        copy: {
          mobile: { weight: 300, color: '#fff', padding: '0.5em 4em', size: 17 },
          tablet: { weight: 300, color: '#fff', padding: '0.5em 4em', size: 17 },
          desktop: { weight: 300, color: '#fff', padding: '0.5em 5em', size: 17 },
        },
        primary: true,
        maxWidth: null,
      },
    },
    {
      maxWidth: '550px',
      padding: {
        mobile: '35px',
        tablet: '35px',
        desktop: '50px 42px',
      },
      margin: {
        mobile: '20px',
        tablet: '20px',
        desktop: '30px',
      },
      xs: 12,
      sm: 12,
      md: true,
      lg: null,
      xl: null,
      heading: {
        text: 'Shop Mens',
        tag: 'h2',
        mobile: { size: 20, weight: 400, textAlign: 'center' },
        tablet: { size: 20, weight: 400 },
        desktop: { size: 24, weight: 400 },
      },
      copy: null,
      img: {
        src: 'shop-mens-landing.svg',
        padding: '20px',
        alt: 'shop Mens',
        maxWidth: null,
        maxHeight: '150px',
      },
      cta: {
        href: '/search/params?section=mens',
        text: 'Start Shopping',
        padding: '0px',
        textTransform: 'capitalize',
        copy: {
          mobile: { weight: 300, color: '#fff', padding: '0.5em 4em', size: 17 },
          tablet: { weight: 300, color: '#fff', padding: '0.5em 4em', size: 17 },
          desktop: { weight: 300, color: '#fff', padding: '0.5em 5em', size: 17 },
        },
        primary: true,
        maxWidth: null,
      },
    },
  ],
};
