export default {
  footer: {
    bgColor: '#171717',
    padding: {
      mobile: '10px, 20px',
      tablet: '30px 15px',
      desktop: '40px 0px',
    },
    margin: null,
    separator: {
      mobile: {
        color: '#fff',
        visible: false,
      },
      tablet: {
        color: '#fff',
        visible: true,
      },
      desktop: {
        color: '#fff',
        visible: true,
      },
    },
    items: [
      {
        grid: {
          xs: 12,
          sm: 2,
          md: null,
          lg: null,
          xl: null,
        },
        padding: {
          mobile: '10px, 20px',
          tablet: '30px 15px',
          desktop: '0px 20px',
        },
        margin: {
          desktop: '0px',
        },
        contentItems: {
          grid: {
            xs: 12,
          },
          items: [
            {
              copy: null,
              heading: null,
              cta: null,
              img: {
                src: 'logo-reverse.svg',
                alt: 'Fliik',
                iconColor: '#fff',
                maxWidth: '75px',
              },
            },
          ],
        },
      },
      {
        grid: {
          xs: 12,
          sm: 6,
        },
        padding: {
          mobile: '10px, 20px',
          tablet: '30px 15px',
          desktop: '0px 20px',
        },
        contentItems: {
          grid: {
            xs: 12,
            sm: 12,
            md: 4,
          },
          items: [
            {
              copy: {
                text: 'About us',
                tag: 'p',
                mobile: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                tablet: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                desktop: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                href: '/about',
                useNativeLink: true,
              },
              heading: null,
              cta: null,
              img: null,
            },
            {
              copy: {
                text: 'Help / Info',
                tag: 'p',
                mobile: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                tablet: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                desktop: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                href: '/help-and-info',
                useNativeLink: true,
              },
              heading: null,
              cta: null,
              img: null,
            },
            {
              copy: {
                text: 'Motivation',
                tag: 'p',
                mobile: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                tablet: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                desktop: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                href: '/motivation',
                useNativeLink: true,
              },
              heading: null,
              cta: null,
              img: null,
            },
            {
              grid: {
                xs: 12,
                sm: true,
              },
              copy: {
                text: 'Cookies',
                tag: 'p',
                mobile: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                tablet: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                desktop: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                href: '/cookies',
                useNativeLink: true,
              },
              heading: null,
              cta: null,
              img: null,
            },
            {
              copy: {
                text: 'Terms and conditions',
                tag: 'p',
                mobile: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                tablet: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                desktop: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                href: '/terms-and-conditions',
                useNativeLink: true,
              },
              heading: null,
              cta: null,
              img: null,
            },
            {
              copy: {
                text: 'Payments',
                tag: 'p',
                mobile: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                tablet: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                desktop: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                href: '/payments',
                useNativeLink: true,
              },
              heading: null,
              cta: null,
              img: null,
            },
            {
              copy: {
                text: 'Developers',
                tag: 'p',
                mobile: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                tablet: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                desktop: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                href: '/developers',
                useNativeLink: true,
              },
              heading: null,
              cta: null,
              img: null,
            },
            {
              copy: {
                text: 'Partner with us',
                tag: 'p',
                mobile: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                tablet: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                desktop: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                href: '/become-a-partner',
                useNativeLink: true,
              },
              heading: null,
              cta: null,
              img: null,
            },
            {
              copy: {
                text: 'Contact',
                tag: 'p',
                mobile: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                tablet: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                desktop: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                href: '/contact',
                useNativeLink: true,
              },
              heading: null,
              cta: null,
              img: null,
            },
            {
              copy: {
                text: ' ',
                tag: 'p',
                mobile: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                tablet: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                desktop: {
                  size: 14,
                  weight: 300,
                  textAlign: 'center',
                  color: '#fff',
                  padding: '0.4em',
                },
                href: '/',
              },
              heading: null,
              cta: null,
              img: null,
            },
          ],
        },
      },
      {
        grid: {
          xs: 12,
          sm: 4,
        },
        padding: {
          mobile: '10px 20px',
          tablet: '30px 15px',
          desktop: '0px 20px',
        },
        contentItems: {
          grid: {
            xs: true,
          },
          items: [
            {
              heading: null,
              copy: null,
              cta: null,
              img: {
                icon: 'Facebook',
                alt: 'facebook',
                iconColor: '#fff',
                iconSize: 'large',
                padding: '10px 0px',
                tooltip: {
                  title: "Sit tight we're quite new...",
                  copy: "We'll be on your favourite social media channels soon!",
                },
              },
            },
            {
              heading: null,
              copy: null,
              cta: null,
              img: {
                icon: 'Instagram',
                alt: 'instagram',
                iconColor: '#fff',
                iconSize: 'large',
                padding: '10px 0px',
                tooltip: {
                  title: "Sit tight we're quite new...",
                  copy: "We'll be on your favourite social media channels soon!",
                },
              },
            },
            {
              heading: null,
              copy: null,
              cta: null,
              img: {
                icon: 'Pinterest',
                alt: 'pinterest',
                iconColor: '#fff',
                iconSize: 'large',
                padding: '10px 0px',
                tooltip: {
                  title: "Sit tight we're quite new...",
                  copy: "We'll be on your favourite social media channels soon!",
                },
              },
            },
          ],
        },
      },
    ],
  },
};
