// TODO: look to remove these exports and reference @affiliate-master/common/web instead
export {
  fastClone,
  toArray,
  toArrayNullable,
  navigateToUrl,
  getSingle,
  srcToHttp,
  delayedCallback,
  isDebug,
  isStringInt,
  getIntFromPrice,
  getCalculatedDiscount,
  getCurrentPrice,
  navigateToPageRefresh,
  getScrollTop,
  setScrollTop,
  stringifySafe,
  commonMultiMatch,
  getLocalStorage,
  setLocalStorage,
  getNode,
  getAllNodes,
  simpleStartCase,
  urlCase,
  urlCaseMatches,
  keyWordsToString,
  isServer,
  betterThrottle,
  crossIncludes,
  createEvent,
  urlReverseCase,
  isInPwa,
  isIos,
  isChrome,
  urlContainsQuery,
  deDupeArray,
} from '@affiliate-master/common/web';
export { getImg } from './common';
